# Generated by Django 4.0 on 2022-06-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_project_images_alter_project_user'),
        ('projectmanager', '0002_project_user'),
    ]

    operations = [
    ]
