# Generated by Django 4.0.5 on 2022-06-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_merge_20220605_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
    ]
